### ISSUE TITLE
Booksleeve MessageQueue Closed

### ISSUE THREAD

**Issue by jrusbatch** [jrusbatch/compilify#30]
This exception began occurring on one of the web server instances. Deploying 51ea03c9f53d40ade0503fd78db4ca47ba0eaa9c stopped the exceptions, but it's hard to tell if they stopped because of the deployment or because of the fix. Unfortunately, I did not subscribe to the `UnhandledTaskException` event on the TaskScheduler, so I have no further information.

Exceptions

[InvalidOperationException: The queue is closed]
   at BookSleeve.MessageQueue.Enqueue(RedisMessage item, Boolean highPri) in C:\Dev\BookSleeve\BookSleeve\MessageQueue.cs:line 71
   at BookSleeve.RedisConnectionBase.EnqueueMessage(RedisMessage message, Boolean queueJump) in C:\Dev\BookSleeve\BookSleeve\RedisConnectionBase.cs:line 872
   at BookSleeve.RedisConnectionBase.ExecuteInt64(RedisMessage message, Boolean queueJump) in C:\Dev\BookSleeve\BookSleeve\RedisConnectionBase.cs:line 788
   at BookSleeve.RedisConnection.BookSleeve.IListCommands.AddLast(Int32 db, String key, Byte[] value, Boolean createIfMissing, Boolean queueJump) in C:\Dev\BookSleeve\BookSleeve\IListCommands.cs:line 453
   at [Compilify.Web.EndPoints.ExecuteEndPoint.OnReceivedAsync(String connectionId, String data) in d:\temp\nekv5d4u.co4\input\Web\EndPoints\ExecuteEndPoint.cs:line 30](https://github.com/Compilify/Compilify/blob/master/Web/EndPoints/ExecuteEndPoint.cs#L30)
   at SignalR.PersistentConnection.<>c__DisplayClass4.<ProcessRequestAsync>b__2(String data)
   at SignalR.Transports.ForeverTransport.ProcessSendRequest()
   at SignalR.Transports.ForeverTransport.ProcessRequest(IReceivingConnection connection)
   at SignalR.PersistentConnection.ProcessRequestAsync(HostContext context)
   at SignalR.Hosting.AspNet.AspNetHost.ProcessRequestAsync(HttpContextBase context)
   at SignalR.Hosting.AspNet.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by jrusbatch** [comment]
Closing for now. Added additional error logging to the background worker, so if it happens again we'll be able to collect more information.
